Telemetry v1
orlandoburli/telemetry-api pull request #1
Opened 2021-01-05 20:10 UTC by GITakeda

Telemetry api version 1.

2021-01-05 22:09 UTC, orlandoburli requested changes
Parabéns pelo trabalho. De uma forma geral, o projeto está muitíssimo bem estruturado, código bem estruturado e enxuto. 

Apenas com atenção a alguns detalhes descritos em todos os arquivos.

Um detalhe sobre o maven wrapper e arquivos binários no git:

O git é um banco de dados de **texto**, sem suporte a arquivos binários. Adicionar arquivos como o jar que está no commit pode ser um problema para o repositório como um todo, uma vez que ele fica para sempre no histórico do mesmo, gerando assim um tamanho gigante no repositório. 

Como é um arquivo binário, o **git** não sabe como gerar as diferenças, logo ele irá repetir esse arquivo a cada commit, gerando assim cópias infinitas do mesmo.

O recomendado para esses casos, caso realmente precise anexar arquivos binários ao git, é usar um plugin chamado **git lfs** que permite um tratamento especial a esses arquivos, de forma a não atrapalhar no desempenho do repositório git em geral.

Recomendo assistir os vídeos do akita sobre git.

https://www.youtube.com/watch?v=6Czd1Yetaac&t=2588s&ab_channel=FabioAkita
https://www.youtube.com/watch?v=6OokP-NE49k&ab_channel=FabioAkita

2021-01-05 22:09 UTC, orlandoburli commented on demo/pom.xml
> +			<version>2.3.4.RELEASE</version>
Verifique se é necessário colocar a versão desse artefato em especifico, pois como ele faz parte do spring-boot, ele tem a sua versão gerenciada pelo "parent"

2021-01-05 22:09 UTC, orlandoburli commented on demo/.mvn/wrapper/MavenWrapperDownloader.java
> +/*
Inicialmente, vou te recomendar remover toda a pasta .mvn, visto que é um requisito que o dev tenha o maven instalado. Depois eu posso te explicar melhor, isso aqui pode gerar um problema para o repositorio git como um todo.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/controller/DeliverymanController.java
> +    @GetMapping("/{id}")
Uma coisa importante, é atenção aos requisitos, as histórias de usuário. A história pedia apenas para **criar** os registros, ou seja, apenas **inserções**/**criações**.

Outra coisa e que esta api não pedia pra fazer o cadastro dos entregadores. Entendo que para efeitos didáticos tudo bem, mas nesse contexto, menos é mais. Isso fará mais sentido para você nas proximas demandas que irei te passar.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/controller/PositionLogController.java
> +public class PositionLogController {
Uma coisa importante, é atenção aos requisitos, as histórias de usuário. A história pedia apenas para **criar** os registros, ou seja, apenas **inserções**/**criações**.

Logo, a partir daqui, todos os outros métodos, inclusive no service e seus testes, podem ser ignorados.

É mais importante focar no método de inserção, no que ele faz, e em validar corretamente os dados de entrada.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/dto/DeliverymanDTO.java
> +//@Data
Não tem problema nenhum usar o lombok. Aqui no ifood se usa bastante também. Porém, não é uma boa prática deixar **códigos comentados** num PR. Se o objetivo é ter histórico, o git serve pra isso.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/dto/DeliverymanDTO.java
> +public class DeliverymanDTO {
Como na classe anterior, comentários no código não devem ir no PR.

Ainda sobre o entregador, inicialmente não serão necessários dados do entregador. Somente o ID do mesmo e a sua localização.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/dto/mapper/DeliverymanMapper.java
> +package com.arthur.takeda.icomida.telemetry.demo.dto.mapper;
Apenas a título de curiosidade/informação, o spring tem uma biblioteca interna para conversão de tipos, teoricamente não precisaria de bibliotecas externas. Depois de uma pesquisada sobre **ConversionService** no spring.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/exception/RestException.java
> +package com.arthur.takeda.icomida.telemetry.demo.exception;
Uma dica, seria renomear esta classe com um nome mais apropriado, por exemplo, como **RestExceptionModel**, pois o nome terminado em exception nos dá a falsa impressão de que se trata de uma classe de **exception**, o que não é o caso.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/model/Deliveryman.java
> +//@Data
Comentários no código.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/model/Deliveryman.java
> +public class Deliveryman {
Como dito acima, este microserviço não precisa dos dados de entregador.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/model/PositionLog.java
> +    private Double latitude;
Uma boa prática aqui seria especificar a precisão dos números. Colocar como **Double** de forma genérica fará com que o JPA crie o campo com uma precisão genérica, que pode não ser a desejada.

Outra coisa importante seria adicionar os validadores JPA para estes campos.

Dica: Pesquise sobre os valores máximo e mínimo de latitude/longitude para armazenar os dados corretamente.

Dica2: Em valores numéricos de precisão, em java, é recomendado usarmos a classe **BigDecimal**. É mais trabalhoso de se usar, mas tem precisão garantida nos números.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/model/PositionLog.java
> +    private Boolean active;
Uma dica sobre dados booleanos, é checar como funciona o banco de dados alvo em que você irá usar. O postgresql suporta tipo booleano? A partir de que versão? Isso são informações importantes na hora de criar um projeto.

Um outro detalhe, a história do usuário fala em status do entregador, que inicialmente teremos apenas o valor **ATIVO**, o que é uma string. A dica aqui é que isso pode ser expandido no futuro para outros status, logo, um booleano pode não ser a melhor opção, sendo **enums** uma opção melhor.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/model/PositionLog.java
> +    private Deliveryman deliveryman;
Como dito anteriormente, como esse microserviço não tem informações do entregador, este campo deveria armazenar apenas o **id** do entregador.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/model/PositionLog.java
> +    private Double battery;
A bateria pode ser um inteiro, ou **Integer**, pois nesse caso não iremos armazenar números após a vírgula, apenas valores de 1 a 100%. Interessante também colocar um validador para isso.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/repository/DeliverymanRepository.java
> +package com.arthur.takeda.icomida.telemetry.demo.repository;
Idem informações sobre o entregador. No futuro podemos ter um repository de deliveryman, mas vindo de outro serviço, ao invés do banco de dados.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/repository/PositionLogRepository.java
> +    public Optional<PositionLog> findByDeliverymanAndActiveAndLast(Long deliveryman_id, Boolean active);
Qual o objetivo deste método? Não vi sua utilização no código.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/test/java/com/arthur/takeda/icomida/telemetry/demo/DemoApplicationTests.java
> +package com.arthur.takeda.icomida.telemetry.demo;
Esta classe não tem uso, logo deveria ser apagada.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/test/java/com/arthur/takeda/icomida/telemetry/demo/service/PositionLogServiceTest.java
> +package com.arthur.takeda.icomida.telemetry.demo.service;
Testes ok, porém todos os testes só testam os _caminhos felizes_. Importante realizar testes que falham, como dados incompletos, incorretos, etc.

2021-01-05 22:09 UTC, orlandoburli commented on demo/src/test/java/com/arthur/takeda/icomida/telemetry/demo/testFactory/DeliverymanTestFactory.java
> +package com.arthur.takeda.icomida.telemetry.demo.testFactory;
Uma dica no futuro, é conhecer a biblioteca **java-faker**, que gera dados para teste. É interessante para não "viciar" os testes com determinados dados .

2021-01-08 20:45 UTC, GITakeda commented on demo/pom.xml
> +			<version>2.3.4.RELEASE</version>
A versão foi removida, realmente não é necessaria.

2021-01-08 20:46 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/controller/DeliverymanController.java
> +    @GetMapping("/{id}")
DeliverymanController foi removido.

2021-01-08 21:00 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/controller/PositionLogController.java
> +public class PositionLogController {
Métodos adicionais foram removidos.

2021-01-08 21:01 UTC, GITakeda commented on demo/.mvn/wrapper/MavenWrapperDownloader.java
> +/*
Pasta .mvn removida.

2021-01-08 21:02 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/dto/DeliverymanDTO.java
> +//@Data
Comentários removidos.

2021-01-08 21:02 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/dto/DeliverymanDTO.java
> +public class DeliverymanDTO {
Comentários removidos.

2021-01-08 21:05 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/dto/mapper/DeliverymanMapper.java
> +package com.arthur.takeda.icomida.telemetry.demo.dto.mapper;
Procurei um pouco sobre o **ConversionService** e achei bem interessante, mas não implementei nessa versão do projeto. Vou implementar ele na próxima vez que tiver a oportunidade.

2021-01-08 21:06 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/exception/RestException.java
> +package com.arthur.takeda.icomida.telemetry.demo.exception;
Classe foi renomeada.

2021-01-08 21:06 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/model/Deliveryman.java
> +//@Data
Comentários removidos.

2021-01-08 21:07 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/model/Deliveryman.java
> +public class Deliveryman {
Classes relacionadas ao Deliveryman foram removidas.

2021-01-08 21:09 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/model/PositionLog.java
> +    private Double latitude;
Ajustei os tipos para BigDecimal e adicionei as restrições corretas para os dados de latitude e longitude.

2021-01-08 21:23 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/model/PositionLog.java
> +    private Boolean active;
O postgresql suporta o tipo booleano, ele aparece a partir da documentação da versão 7.1 [https://www.postgresql.org/docs/7.1/datatype-boolean.html](url).
O status do entregador estava como string temporariamente eu decidi me focar no que era mais importante de acordo com a solicitação, mas concordo que enums são uma opção melhor.

2021-01-08 21:24 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/model/PositionLog.java
> +    private Deliveryman deliveryman;
Campo modificado para guardar apenas o id do entregador.

2021-01-08 21:25 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/model/PositionLog.java
> +    private Double battery;
Eu estava em dúvida nesse, mas realmente faz mais sentido guardar apenas como valores inteiros. O validador de valor máximo e mínimo foi adicionado também.

2021-01-08 21:25 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/repository/DeliverymanRepository.java
> +package com.arthur.takeda.icomida.telemetry.demo.repository;
DeliverymanRepository foi removido.

2021-01-08 21:27 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/repository/PositionLogRepository.java
> +    public Optional<PositionLog> findByDeliverymanAndActiveAndLast(Long deliveryman_id, Boolean active);
Esse método busca o ultimo registro de log para um determinado id de entregador, como vamos precisar de algo parecido futuramente eu achei interessante já deixar um método pronto.

2021-01-08 21:27 UTC, GITakeda commented on demo/src/test/java/com/arthur/takeda/icomida/telemetry/demo/DemoApplicationTests.java
> +package com.arthur.takeda.icomida.telemetry.demo;
Classe foi apagada.

2021-01-08 21:28 UTC, GITakeda commented on demo/src/test/java/com/arthur/takeda/icomida/telemetry/demo/service/PositionLogServiceTest.java
> +package com.arthur.takeda.icomida.telemetry.demo.service;
Os testes com dados incorretos foram adicionados em outro arquivo com testes voltados a classe PositionLogRepository.

2021-01-08 21:29 UTC, GITakeda commented on demo/src/test/java/com/arthur/takeda/icomida/telemetry/demo/testFactory/DeliverymanTestFactory.java
> +package com.arthur.takeda.icomida.telemetry.demo.testFactory;
Procurei sobre e utilizei nos métodos do testFactory.

2021-01-09 15:15 UTC, orlandoburli requested changes
Muito bom, mais uma vez. Apenas alguns pequenos detalhes ali na implementação, no que tange as anotações, e alguns atributos privados, de resto tudo ok.

2021-01-09 15:15 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/dto/PositionLogDTO.java
> +    @DecimalMax(value = "90")
Apenas uma leve melhoria, quando vc tem anotações cujo único atributo é **value**, você pode simplificar a anotação omitindo o texto **value =**, ficando assim:

`@DecimalMax("90")`

2021-01-09 15:15 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/exception/RestExceptionModel.java
> +    HttpStatus httpStatus;
Como estes atributos possuem getter's e setter's, eles deveriam estar privados.

2021-01-09 15:15 UTC, orlandoburli commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/repository/PositionLogRepository.java
> +    public Optional<PositionLog> findByDeliverymanAndActiveAndLast(Long deliveryman_id, Boolean active);
Ok

2021-01-09 15:15 UTC, orlandoburli commented on demo/src/test/java/com/arthur/takeda/icomida/telemetry/demo/repository/PositionLogRepositoryTest.java
> +        positionLog.setLatitude(new BigDecimal("91"));
Apenas um detalhe, BigDecimal aceita números no seu construtor, não teria necessidade de ser uma string, na verdade creio ser mais performático passar como número.

2021-01-11 16:49 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/dto/PositionLogDTO.java
> +    @DecimalMax(value = "90")
Muito bom saber disso, deixa o código bem limpo. Todos os **value =** foram removidos.

2021-01-11 16:50 UTC, GITakeda commented on demo/src/main/java/com/arthur/takeda/icomida/telemetry/demo/exception/RestExceptionModel.java
> +    HttpStatus httpStatus;
Visibilidade dos atributos modificados.

2021-01-11 16:54 UTC, GITakeda commented on demo/src/test/java/com/arthur/takeda/icomida/telemetry/demo/repository/PositionLogRepositoryTest.java
> +        positionLog.setLatitude(new BigDecimal("91"));
Para valores decimais não é recomendado passar como numero por falta de precisão, pensei que isso se aplicava para valores inteiros também. Mas realmente não tem diferença no resultado com números inteiros. Os parâmetros foram modificados.

2021-07-26 12:44 UTC, merged